faiss_db:
  collection_name: "document_portal"

embedding_model:
  provider: "openaiembeddings"
  model_name: "text-embedding-ada-002"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "qwen/qwen3-32b"
    temperature: 0
    max_output_tokens: 2048


